// <auto-generated />
using System;
using GrowsmartAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrowsmartAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322054434_InitialMySql")]
    partial class InitialMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GrowsmartAPI.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "dueDate");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isRead");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GrowsmartAPI.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Category")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<DateTime>("DatePlanted")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DatePlanted")
                        .HasAnnotation("Relational:JsonPropertyName", "datePlanted");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("HealthStatus")
                        .HasAnnotation("Relational:JsonPropertyName", "healthStatus");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsIndoor")
                        .HasAnnotation("Relational:JsonPropertyName", "isIndoor");

                    b.Property<DateTime?>("LastFertilizedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastFertilizedAt")
                        .HasAnnotation("Relational:JsonPropertyName", "lastFertilizedAt");

                    b.Property<DateTime?>("LastWateredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastWateredAt")
                        .HasAnnotation("Relational:JsonPropertyName", "lastWateredAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Species")
                        .HasAnnotation("Relational:JsonPropertyName", "species");

                    b.Property<string>("SunlightRequirement")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SunlightRequirement")
                        .HasAnnotation("Relational:JsonPropertyName", "sunlightRequirement");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.Property<int>("WaterFrequencyDays")
                        .HasColumnType("int")
                        .HasColumnName("WaterFrequencyDays")
                        .HasAnnotation("Relational:JsonPropertyName", "waterFrequencyDays");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("GrowsmartAPI.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GardenSize")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "gardenSize");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<string>("PrimaryInterest")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "primaryInterest");

                    b.Property<bool>("ReceiveReminders")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "receiveReminders");

                    b.Property<bool>("ReceiveWeatherAlerts")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "receiveWeatherAlerts");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "userType");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("GrowsmartAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GrowsmartAPI.Models.Notification", b =>
                {
                    b.HasOne("GrowsmartAPI.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrowsmartAPI.Models.Plant", b =>
                {
                    b.HasOne("GrowsmartAPI.Models.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrowsmartAPI.Models.Profile", b =>
                {
                    b.HasOne("GrowsmartAPI.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("GrowsmartAPI.Models.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrowsmartAPI.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Plants");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
